// Auth types
export const SET_AUTH_TOKEN = 'AUTH/SET_AUTH_TOKEN';
export const SET_USER = 'AUTH/SET_USER';
export const SET_IS_LOGGED_IN = 'AUTH/SET_IS_LOGGED_IN';
export const SET_IS_LOGGING_IN = 'AUTH/SET_IS_LOGGING_IN';

// Server types
export const SET_USERS_ONLINE = 'SERVER/USERS_ONLINE';
export const SET_HUB_CONNECTION = 'SERVER/SET_HUBCONNECTION';
export const SET_IS_HUB_CONNECTION_LOADING = 'SERVER/IS_HUB_CONNECTION_LOADING';

// QuizRoom types
export const SET_QUIZ_ROOM = "QUIZ_ROOM/SET_QUIZ_ROOM";
export const SET_IS_ADDING_USER_TO_QUIZ_ROOM = "QUIZ_ROOM/SET_IS_ADDING_USER_TO_QUIZ_ROOM";
export const SET_QUIZ_ROOM_TIME = "QUIZ_ROOM/SET_QUIZ_ROOM_TIME";
export const SET_QUIZ_ROOM_PHASE = "QUIZ_ROOM/SET_QUIZ_ROOM_PHASE";
export const SET_QUIZ_RESULTS = "QUIZ_ROOM/SET_QUIZ_RESULTS";
export const SET_QUIZ_ROOM_USERS_ONLINE = "QUIZ_ROOM/SET_QUIZ_ROOM_USERS_ONLINE";
export const SET_CURRENT_QUESTION = "QUIZ_ROOM/SET_CURRENT_QUESTION";
export const SET_CURRENT_QUESTION_RESULT = "QUIZ_ROOM/SET_CURRENT_QUESTION_RESULT";